CI workflow to validate webhook templates
TheThingsNetwork/lorawan-webhook-templates pull request #36
Opened 2021-06-21 17:55 UTC by neoaggelos

#### Summary

Add CI workflow to validate webhook templates changes on pull requests.

#### Changes

- Add `validate.go` program that loads webhook templates from a local directory and validates the `TemplateStore` implementation
- Add GitHub workflow for running validate on each pull request and pushes to master. Binary and go modules are cached so workflow only takes a couple of seconds.
- Fix TagoIO and Ubidots webhook templates caught by the tool --> there is a mismatch on their ID vs the filename.

#### Notes for Reviewers

- The webhook template ID changes should not affect users that setup their integrations from the Console, since the console only uses the `ListTemplates` RPC.
- Changed the webhook template IDs to match the ones that existing integrations will already have, to avoid breaking something by accident. 

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [X] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

2021-06-22 06:24 UTC, nejraselimovic approved these changes

2021-06-22 06:54 UTC, htdvisser requested changes
I would prefer to do the imports the other way around; instead of having `lorawan-stack` as a dependency of `lorawan-webhook-templates`, maybe it would be better to define the structs in `lorawan-webhook-templates` and have `lorawan-stack` import those.

Also: Please see my message on Slack.

2021-06-22 08:18 UTC, adriansmares commented
> I would prefer to do the imports the other way around; instead of having `lorawan-stack` as a dependency of `lorawan-webhook-templates`, maybe it would be better to define the structs in `lorawan-webhook-templates` and have `lorawan-stack` import those.
> 
> Also: Please see my message on Slack.

I initially wanted to just press approve, but I actually agree with this suggestion after giving it some thought:
- No cyclical dependencies
- The variant in this PR also in a sense tests the store implementation as well, which is not ideal (albeit useful in a sense)
- Checking if the YAML serialization / de-serialization passes suffices for this class of bugs

A long term solution would be a YAML schema, but I can accept just testing the serialization and a backlog issue for now.

2021-06-22 09:22 UTC, adriansmares approved these changes
I would make the `schema` package top level, and make sure to use it in `lorawan-stack`.

2021-06-24 08:38 UTC, htdvisser commented on .github/workflows/validate.yml
> +        key: ${{ runner.os }}-validate-${{ hashFiles('schema/**.go') }}
Please also include `go.mod`/`go.sum` so that we can update dependencies

2021-06-24 08:38 UTC, htdvisser commented on schema/cmd/validate.go
> +	b, err := ioutil.ReadFile(templateYml)
Since Go 1.16 package `ioutil` is deprecated, please use `os.ReadFile` instead.

2021-06-24 08:38 UTC, htdvisser commented on schema/cmd/validate.go
> +	os.Exit(rc)
You never seem to modify `rc`, so it's always `0`.

2021-06-24 08:38 UTC, htdvisser commented on schema/go.mod
> +module go.thethings.network/lorawan-webhook-templates/schema
This is not found. Either add it to https://github.com/TheThingsNetwork/govanityurls/blob/master/vanity.yaml or use github.com/TheThingsIndustries/lorawan-webhook-templates.

2021-06-28 07:14 UTC, htdvisser approved these changes

2021-06-28 07:14 UTC, htdvisser commented on schema/cmd/validate.go
> +					rc = 1
The race detector probably won't like this

2021-07-01 09:18 UTC, merged