Update akenza connector
TheThingsNetwork/lorawan-webhook-templates pull request #63
Opened 2022-05-10 13:13 UTC by SavinNiederer

#### Summary

Updates the akenza webhook to work with the new akenza platform.

#### Changes

- Updates the akenza webhook to work with the new akenza platform.

#### Notes for Reviewers

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

2022-05-10 13:20 UTC, mariusgiger commented on akenza.yml
> +format: json
format json is added twice

2022-05-11 13:27 UTC, nejraselimovic commented on akenza.yml
> +format: json
`create-downlink-api-key` as well. Did you test this template?

2022-05-11 14:32 UTC, nejraselimovic requested changes
I just tested this template using a local TTS instance and Postman simultaneously, and I found an issue.

If you use `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>` the data doesn't show up on akenza. On the other hand, if you use `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>&deviceId=<device-id>` or `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>&deviceId=<device-id>&topic=<topic-name>`, in both cases data shows up on akenza.

The `base-url` in this template is defined as `https://data-gateway.akenza.io/v3/capture?secret={uplink_secret}`, i.e. it's missing the `deviceId` part to make it work. However, if you add that part and define `https://data-gateway.akenza.io/v3/capture?secret={uplink_secret}&deviceId={device_id}`, the predefined maximum base URL length is exceeded.

I guess it will be necessary to make the endpoint URL format shorter? Your thoughts @adriansmares?

2022-05-11 17:19 UTC, adriansmares commented
The 64 character limitation applies to message paths (`uplink_message`), but not to `base_url`. So it is entirely possible to put the full URL there for now, and to use just `""` as a message path.

2022-05-12 12:21 UTC, SavinNiederer commented
> If you use `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>` the data doesn't show up on akenza. On the other hand, if you use `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>&deviceId=<device-id>` or `https://data-gateway.akenza.io/v3/capture?secret=<secret-value>&deviceId=<device-id>&topic=<topic-name>`, in both cases data shows up on akenza.
> 
> The `base-url` in this template is defined as `https://data-gateway.akenza.io/v3/capture?secret={uplink_secret}`, i.e. it's missing the `deviceId` part to make it work. However, if you add that part and define `https://data-gateway.akenza.io/v3/capture?secret={uplink_secret}&deviceId={device_id}`, the predefined maximum base URL length is exceeded.

The `deviceId` and `topic` are taken from the uplink body. I verified that the URL is correct using our current implementation which uses the default webhook instead of the akenza template.
![image](https://user-images.githubusercontent.com/36765866/168054040-f5e30d51-22cc-48bb-9427-4760ea7fa080.png)

Sent test uplink
![image](https://user-images.githubusercontent.com/36765866/168057175-7a612e6f-7fe9-4389-9079-2baef49dfadd.png)

uplink received on akenza
![image](https://user-images.githubusercontent.com/36765866/168055289-e512e297-e6d1-47b3-b9ff-4d9a3287312f.png)

Here some documentation links to recreate this:
https://docs.akenza.io/get-started/your-integration/the-things-network
https://docs.akenza.io/get-started/your-data-flow
https://docs.akenza.io/tutorials/add-devices/how-to-integrate-a-decentlab-sensor-with-ttn-on-akenza select passthrought as a device type and send the uplink manually from TTN side

2022-05-13 08:28 UTC, nejraselimovic approved these changes

2022-05-13 08:28 UTC, merged