Add ALSO IoT Platform
TheThingsNetwork/lorawan-webhook-templates pull request #87
Opened 2023-09-12 13:06 UTC by epiller

#### Summary

Added ALSO IoT Platform.

#### Changes

- Added ALSO IoT Platform webhook template.

2023-09-12 13:06 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/TheThingsNetwork/lorawan-webhook-templates?pullRequest=87) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/TheThingsNetwork/lorawan-webhook-templates?pullRequest=87) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/TheThingsNetwork/lorawan-webhook-templates?pullRequest=87) it.</sub>

2023-09-13 19:11 UTC, nejraselimovic requested changes

2023-09-13 19:11 UTC, nejraselimovic commented on also-iot-platform.yml
> +    description: Network token from your device's connectivity settings.
```suggestion
    description: Network token from your device's connectivity settings on ALSO IoT
```

2023-09-13 19:11 UTC, nejraselimovic commented on also-iot-platform.yml
> +template-id: also-iot-platform
You need to add this template ID to templates.yml file

2023-09-21 18:25 UTC, epiller commented on also-iot-platform.yml
> +    description: Network token from your device's connectivity settings.
Done

2023-09-21 18:27 UTC, epiller commented
Requested changes done.

2023-09-22 20:23 UTC, closed without merging

2023-09-22 20:47 UTC, nejraselimovic commented
hey @epiller I'm so sorry but I somehow managed to mess up this PR :') I replaced it with #88. While waiting for the approval to merge it, do you happen to have any documentation for this?

2023-09-22 20:49 UTC, epiller commented
Opusteno 😂
Our main documentation is here: https://docs.allthingstalk.com and it applies to all of our instances (AllThingsTalk Maker, ALSO IoT Platform, others).

2023-10-02 08:12 UTC, epiller commented
@nejraselimovic I still don't see ALSO IoT Platform on TheThingsNetwork webhooks. Do you have any idea when it will be available? Thanks!

2023-10-02 12:06 UTC, nejraselimovic commented
> @nejraselimovic I still don't see ALSO IoT Platform on TheThingsNetwork webhooks. Do you have any idea when it will be available? Thanks!

Hey Vanja, it should become available with the next TTS release. I see that the merge deadline for v3.28.0 is October 18, I guess it was postponed a bit because of the conference.