Upload CSV to partner portal
TheThingsNetwork/lorawan-webhook-templates pull request #96
Opened 2024-06-03 09:24 UTC by LDannijs

#### Summary

Add a script, like the device repository, to sync the contents of this repo to Airtable so it can be used with the Partner Portal.

#### Changes

- Add a script that converts all the templates into a csv
- Update workflow to automate syncing to airtable

#### Notes for Reviewers

@benolayinka let me know if this seems correct.

#### Checklist

- [ ] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

2024-06-13 06:30 UTC, KrishnaIyer requested changes
The `node_modules` folder is not supposed to be checked in to version control. Please add that to `.gitignore` and delete it here.

2024-06-13 06:30 UTC, KrishnaIyer commented on .github/workflows/validate.yml
> +          --data-binary "@bin/templates.csv"
Let's separate this out to a separate action. Ex: `upload-to-airtable.yml` and make that action run on a push to the `master` branch.

2024-06-13 11:40 UTC, KrishnaIyer commented on .github/workflows/upload-airtable.yml
> +          curl -X POST ${{ secrets.AIRTABLE_WEBHOOKS_API_ENDPOINT }} \
`-X` is unnecessary since `curl` implies it.

2024-06-13 11:40 UTC, KrishnaIyer commented on .github/workflows/validate.yml
> +        run: ./bin/validate
New line at end of file. Please fix you editor.

2024-06-13 11:40 UTC, KrishnaIyer commented on .gitignore
> +bin/node_modules
New line at end of file. Please fix you editor.

2024-06-13 11:40 UTC, KrishnaIyer commented on bin/csv.js
> +
Can you write some tests for this code?

2024-06-13 12:25 UTC, LDannijs commented on bin/csv.js
> +
What do you mean with tests? If the csv is correct?

2024-06-13 12:30 UTC, KrishnaIyer commented on bin/csv.js
> +
Yes

2024-06-13 12:42 UTC, LDannijs commented on bin/csv.js
> +
I have ran it through various CSV checkers and the CSV is valid

2024-06-17 08:10 UTC, KrishnaIyer commented on bin/csv.js
> +
Validity is meant for syntax. How do you ensure that your generated CSV is actually correct, that all the correct fields are added?

2024-06-17 08:14 UTC, KrishnaIyer approved these changes
I'm conditionally approving this out of necessity (as discussed on Slack). There are no tests to validate if `csv.js` file has all the correct fields. I trust that this is manually tested for now.

2024-06-17 08:53 UTC, LDannijs commented on bin/csv.js
> +
I tested if the csv was correct with the same tools as when i did for the devices and it was correct, but i am noticing we dont need the logo so ill fix that.

2024-06-17 08:56 UTC, LDannijs commented
I have manually tested it with the airtable Sync API, and all the fields look correct.

![image](https://github.com/TheThingsNetwork/lorawan-webhook-templates/assets/117638911/9407a422-20e7-4b45-85af-f23f4abfc822)

2024-06-17 09:02 UTC, merged