Stack documentation URL
TheThingsNetwork/lorawan-webhook-templates pull request #98
Opened 2024-08-14 12:18 UTC by LDannijs

#### Summary

Add a URL to The Things Industries documentation of integrations
@felixheins wanted this for the Partner Portal

#### Changes

- add `stack-documentation-url`
- Update broken URLs

#### Notes for Reviewers

@KrishnaIyer is this properly implemented?

#### Checklist

- [x] Scope: The referenced issue is addressed, there are no unrelated changes.
- [x] Compatibility: The changes are backwards compatible, they don't break existing deployments.
- [x] Testing: The changes are tested.
- [ ] Documentation: Relevant documentation is added or updated.

2024-08-14 12:36 UTC, felixheins commented
Thanks @LDannijs . Just to show an example: 

In the partner portal, we want to keep visitors on our pages and not lead them out. Not only for lead development reasons but also because partner links break and we can't control them. 

https://partners.thethingsindustries.com/integrations-details/datacake/r/reccQxsCgQ0jVm2zW

2024-08-15 16:47 UTC, KrishnaIyer requested changes
Implementation looks ok to me. Some of these vendors (Ex: `iot-factory.yml`) don't have the new URL. Is that intended?

2024-08-15 16:47 UTC, KrishnaIyer commented on schema/lorawan_webhook_templates.go
> +	StackDocumentationURL string                 `yaml:"stack-documentation-url"`
The Things Stack; so maybe `TTSDocumentationURL`

2024-08-16 07:06 UTC, LDannijs commented
Yes some don't because they don't have any documentation.

2024-08-19 08:10 UTC, KrishnaIyer approved these changes

2024-09-11 11:27 UTC, merged